# Generated by Django 4.2.7 on 2024-01-14 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registration_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roll",
            field=models.CharField(
                choices=[("Base User", "Base User"), ("Admin", "Admin"), ("Super Admin", "Super Admin")],
                default="Base User",
                max_length=20,
            ),
        ),
    ]
