# Generated by Django 4.2.7 on 2024-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_userprofile_registration_datetime_userprofile_roll"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="roll",
            new_name="role",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="provider",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
