# Generated by Django 4.2.7 on 2024-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_roll_userprofile_role_userprofile_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
