# Generated by Django 4.2.7 on 2024-01-15 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="image",
        ),
    ]
